# Generated by Django 5.2.1 on 2025-06-14 09:54

import django.db.models.deletion
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الفعالية')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='معرف URL')),
                ('description', models.TextField(verbose_name='وصف الفعالية')),
                ('short_description', models.CharField(blank=True, help_text='وصف مختصر للعرض في الشريط العلوي', max_length=255, verbose_name='وصف مختصر')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('banner_image', models.ImageField(help_text='صورة مصغرة للعرض في الشريط العلوي (مقاس موصى به: 1200×200)', upload_to=events.models.upload_event_image, verbose_name='صورة الشريط العلوي')),
                ('cover_image', models.ImageField(help_text='صورة كبيرة للعرض في معرض الشرائح (مقاس موصى به: 1920×600)', upload_to=events.models.upload_event_image, verbose_name='صورة الغلاف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('display_in', models.CharField(choices=[('banner', 'شريط علوي'), ('slider', 'معرض شرائح'), ('both', 'كلاهما')], default='both', max_length=10, verbose_name='مكان العرض')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('registration_url', models.URLField(blank=True, verbose_name='رابط التسجيل')),
                ('button_text', models.CharField(default='اعرف المزيد', max_length=50, verbose_name='نص الزر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'فعالية',
                'verbose_name_plural': 'الفعاليات',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=events.models.upload_event_image, verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='وصف الصورة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.event', verbose_name='الفعالية')),
            ],
            options={
                'verbose_name': 'صورة الفعالية',
                'verbose_name_plural': 'صور الفعاليات',
                'ordering': ['order'],
            },
        ),
    ]
