# Generated by Django 5.2.4 on 2025-07-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='نص الزر بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='وصف الفعالية بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='الموقع بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='وصف مختصر بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان الفعالية بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='وصف الصورة بالإنجليزية'),
        ),
    ]
