# Generated by Django 5.2.1 on 2025-05-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='اسم الموقع')),
                ('site_description', models.TextField(blank=True, verbose_name='وصف الموقع')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='الشعار')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='أيقونة الموقع')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('facebook', models.URLField(blank=True, verbose_name='فيسبوك')),
                ('twitter', models.URLField(blank=True, verbose_name='تويتر')),
                ('instagram', models.URLField(blank=True, verbose_name='انستغرام')),
                ('linkedin', models.URLField(blank=True, verbose_name='لينكد إن')),
                ('primary_color', models.CharField(choices=[('#1e88e5', 'أزرق'), ('#43a047', 'أخضر'), ('#e53935', 'أحمر'), ('#fb8c00', 'برتقالي'), ('#6d4c41', 'بني')], default='#1e88e5', max_length=7, verbose_name='اللون الرئيسي')),
                ('primary_color_rgb', models.CharField(blank=True, editable=False, max_length=15, verbose_name='اللون الرئيسي (RGB)')),
                ('enable_dark_mode', models.BooleanField(default=True, verbose_name='تفعيل الوضع الداكن')),
                ('default_dark_mode', models.BooleanField(default=False, verbose_name='الوضع الداكن افتراضيًا')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
