# Generated by Django 5.2.4 on 2025-07-11 06:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاشتراك')),
            ],
            options={
                'verbose_name': 'اشتراك في النشرة البريدية',
                'verbose_name_plural': 'اشتراكات النشرة البريدية',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='اسم الموقع')),
                ('site_description', models.TextField(blank=True, verbose_name='وصف الموقع')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='الشعار')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='أيقونة الموقع')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('facebook', models.URLField(blank=True, verbose_name='فيسبوك')),
                ('twitter', models.URLField(blank=True, verbose_name='تويتر')),
                ('instagram', models.URLField(blank=True, verbose_name='انستغرام')),
                ('linkedin', models.URLField(blank=True, verbose_name='لينكد إن')),
                ('primary_color', models.CharField(choices=[('#1e88e5', 'أزرق'), ('#43a047', 'أخضر'), ('#e53935', 'أحمر'), ('#fb8c00', 'برتقالي'), ('#6d4c41', 'بني'), ('#0357b5', 'ازرق غامق')], default='#1e88e5', max_length=7, verbose_name='اللون الرئيسي')),
                ('primary_color_rgb', models.CharField(blank=True, editable=False, max_length=15, verbose_name='اللون الرئيسي (RGB)')),
                ('enable_dark_mode', models.BooleanField(default=True, verbose_name='تفعيل الوضع الداكن')),
                ('default_dark_mode', models.BooleanField(default=False, verbose_name='الوضع الداكن افتراضيًا')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('subtitle', models.CharField(max_length=150, verbose_name='العنوان الفرعي')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='الصورة')),
                ('primary_button_text', models.CharField(max_length=50, verbose_name='نص الزر الرئيسي')),
                ('primary_button_url', models.CharField(max_length=200, verbose_name='رابط الزر الرئيسي')),
                ('secondary_button_text', models.CharField(blank=True, max_length=50, verbose_name='نص الزر الثانوي')),
                ('secondary_button_url', models.CharField(blank=True, max_length=200, verbose_name='رابط الزر الثانوي')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'عنصر السلايدر',
                'verbose_name_plural': 'عناصر السلايدر',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='المفتاح')),
                ('content_ar', ckeditor.fields.RichTextField(verbose_name='المحتوى بالعربية')),
                ('content_en', ckeditor.fields.RichTextField(verbose_name='المحتوى بالإنجليزية')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'محتوى ثابت',
                'verbose_name_plural': 'محتويات ثابتة',
            },
        ),
    ]
