# Generated by Django 5.0.1 on 2025-05-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color_rgb',
            field=models.CharField(blank=True, editable=False, max_length=15, verbose_name='اللون الرئيسي (RGB)'),
        ),
    ]
