# Generated by Django 5.2.4 on 2025-07-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='phone_whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف واتساب'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.URLField(blank=True, verbose_name='واتساب'),
        ),
    ]
