# Generated by Django 5.2.1 on 2025-06-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاشتراك')),
            ],
            options={
                'verbose_name': 'اشتراك في النشرة البريدية',
                'verbose_name_plural': 'اشتراكات النشرة البريدية',
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(choices=[('#1e88e5', 'أزرق'), ('#43a047', 'أخضر'), ('#e53935', 'أحمر'), ('#fb8c00', 'برتقالي'), ('#6d4c41', 'بني'), ('#0357b5', 'ازرق غامق')], default='#1e88e5', max_length=7, verbose_name='اللون الرئيسي'),
        ),
    ]
