# Generated by Django 5.2.1 on 2025-12-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_phone_whatsapp_sitesettings_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='free_shipping_threshold',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='الحد الأدنى للطلب للحصول على شحن مجاني (0 = لا يوجد شحن مجاني)', max_digits=10, verbose_name='حد الشحن المجاني'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shipping_enabled',
            field=models.BooleanField(default=True, help_text='تفعيل أو إلغاء تفعيل أجور الشحن', verbose_name='تفعيل أجور الشحن'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shipping_fee_amman',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='أجور التوصيل داخل عمان', max_digits=10, verbose_name='أجور النقل - عمان'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shipping_fee_other',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='أجور التوصيل لباقي محافظات الأردن', max_digits=10, verbose_name='أجور النقل - باقي المحافظات'),
        ),
    ]
