# Generated by Django 5.2.1 on 2025-06-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newsletter_alter_sitesettings_primary_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('subtitle', models.CharField(max_length=150, verbose_name='العنوان الفرعي')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='الصورة')),
                ('primary_button_text', models.CharField(max_length=50, verbose_name='نص الزر الرئيسي')),
                ('primary_button_url', models.CharField(max_length=200, verbose_name='رابط الزر الرئيسي')),
                ('secondary_button_text', models.CharField(blank=True, max_length=50, verbose_name='نص الزر الثانوي')),
                ('secondary_button_url', models.CharField(blank=True, max_length=200, verbose_name='رابط الزر الثانوي')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'عنصر السلايدر',
                'verbose_name_plural': 'عناصر السلايدر',
                'ordering': ['order'],
            },
        ),
    ]
