# Generated by Django 5.2.1 on 2025-12-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_shipping_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='emails_received',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الرسائل المستلمة'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تم التحقق'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='last_email_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر رسالة مرسلة'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='unsubscribe_token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='رمز إلغاء الاشتراك'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='verification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إرسال التحقق'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='رمز التحقق'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحقق'),
        ),
    ]
