# Generated by Django 5.2.1 on 2026-04-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_newsletter_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideritem',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Subtitle (EN)'),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title (EN)'),
        ),
    ]
