# Generated by Django 5.2.1 on 2026-04-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seed_about_static_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='catalog_ar',
            field=models.FileField(blank=True, null=True, upload_to='catalogs/', verbose_name='الكتالوج (عربي)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='catalog_en',
            field=models.FileField(blank=True, null=True, upload_to='catalogs/', verbose_name='Catalog (English)'),
        ),
    ]
