# Generated by Django 5.2.1 on 2026-04-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_catalog_ar_sitesettings_catalog_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='company_profile_ar',
            field=models.FileField(blank=True, null=True, upload_to='profiles/', verbose_name='بروفايل الشركة (عربي)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_profile_en',
            field=models.FileField(blank=True, null=True, upload_to='profiles/', verbose_name='Company Profile (English)'),
        ),
    ]
