# Generated by Django 5.2.13 on 2026-04-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesettings_marketing_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الفرع')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='Branch Name')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('address_en', models.TextField(blank=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('working_hours', models.CharField(blank=True, max_length=200, verbose_name='ساعات العمل')),
                ('working_hours_en', models.CharField(blank=True, max_length=200, verbose_name='Working Hours')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pickup_enabled',
            field=models.BooleanField(default=False, help_text='تفعيل خيار الاستلام من الفرع للعملاء', verbose_name='تفعيل الاستلام من الفرع'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='مفتاح OpenRouter API'),
        ),
    ]
