# Generated by Django 5.2.1 on 2026-04-23 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_branch_sitesettings_pickup_enabled_and_more'),
        ('products', '0006_add_show_prices_to_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='canonical_domain',
            field=models.URLField(blank=True, help_text='النطاق الرئيسي للموقع مثل https://www.example.com', verbose_name='النطاق الأساسي'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_sitemap',
            field=models.BooleanField(default=True, help_text='إنشاء ملف sitemap.xml تلقائياً', verbose_name='تفعيل خريطة الموقع'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_structured_data',
            field=models.BooleanField(default=True, help_text='إضافة بيانات JSON-LD لمحركات البحث (Schema.org)', verbose_name='تفعيل البيانات المنظمة'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='مثال: G-XXXXXXXXXX أو UA-XXXXXXXX-X', max_length=30, verbose_name='معرف Google Analytics'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_search_console_code',
            field=models.CharField(blank=True, help_text='رمز التحقق من ملكية الموقع في Google Search Console', max_length=100, verbose_name='رمز تحقق Google Search Console'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, help_text='الصورة التي تظهر عند مشاركة الموقع على وسائل التواصل (1200x630 بيكسل)', null=True, upload_to='seo/', verbose_name='صورة المشاركة الافتراضية'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_description',
            field=models.TextField(blank=True, help_text='الوصف الذي يظهر تحت العنوان في نتائج البحث (150-160 حرف)', max_length=160, verbose_name='وصف SEO للموقع'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_keywords',
            field=models.TextField(blank=True, help_text='كلمات مفتاحية مفصولة بفواصل تصف نشاط الموقع', verbose_name='الكلمات المفتاحية العامة'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_title',
            field=models.CharField(blank=True, help_text='العنوان الذي يظهر في نتائج محركات البحث (60-70 حرف)', max_length=70, verbose_name='عنوان SEO للموقع'),
        ),
        migrations.CreateModel(
            name='SEOKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, verbose_name='الكلمة المفتاحية')),
                ('keyword_en', models.CharField(blank=True, max_length=200, verbose_name='Keyword (English)')),
                ('level', models.CharField(choices=[('site', 'مستوى الموقع'), ('category', 'مستوى الفئة'), ('product', 'مستوى المنتج'), ('competitor', 'منافس')], default='site', max_length=20, verbose_name='المستوى')),
                ('search_volume', models.PositiveIntegerField(blank=True, default=0, verbose_name='حجم البحث الشهري')),
                ('competition', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي')], default='medium', max_length=10, verbose_name='مستوى المنافسة')),
                ('is_competitor', models.BooleanField(default=False, verbose_name='كلمة منافس')),
                ('competitor_url', models.URLField(blank=True, verbose_name='رابط المنافس')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_keywords', to='products.category', verbose_name='الفئة')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_keywords', to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'كلمة مفتاحية SEO',
                'verbose_name_plural': 'كلمات مفتاحية SEO',
                'ordering': ['-search_volume', 'keyword'],
                'unique_together': {('keyword', 'level', 'category', 'product')},
            },
        ),
    ]
