# Generated by Django 5.2.13 on 2026-04-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesettings_canonical_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_title',
            field=models.CharField(blank=True, help_text='العنوان الذي يظهر في نتائج محركات البحث', max_length=200, verbose_name='عنوان SEO للموقع'),
        ),
    ]
