# Generated by Django 5.2.13 on 2026-04-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_increase_seo_title_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_bg_color',
            field=models.CharField(blank=True, default='#1b5e20', help_text='لون الخلفية بصيغة HEX مثل #1b5e20', max_length=7, verbose_name='لون خلفية الشريط'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_icon_1',
            field=models.CharField(blank=True, default='fas fa-truck-fast', help_text='كلاس أيقونة Font Awesome مثل fas fa-truck-fast', max_length=50, verbose_name='أيقونة 1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_icon_2',
            field=models.CharField(blank=True, default='fas fa-shield-check', help_text='كلاس أيقونة Font Awesome', max_length=50, verbose_name='أيقونة 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_icon_3',
            field=models.CharField(blank=True, default='fas fa-rotate-left', help_text='كلاس أيقونة Font Awesome', max_length=50, verbose_name='أيقونة 3'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_text_1_ar',
            field=models.CharField(blank=True, default='شحن مجاني للطلبات فوق 200 د.أ', max_length=100, verbose_name='نص 1 (عربي)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_text_1_en',
            field=models.CharField(blank=True, default='Free shipping on orders over 200 JOD', max_length=100, verbose_name='نص 1 (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_text_2_ar',
            field=models.CharField(blank=True, default='منتجات أصلية 100% مع ضمان', max_length=100, verbose_name='نص 2 (عربي)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_text_2_en',
            field=models.CharField(blank=True, default='100% Original products with warranty', max_length=100, verbose_name='نص 2 (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_text_3_ar',
            field=models.CharField(blank=True, default='إرجاع سهل', max_length=100, verbose_name='نص 3 (عربي)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_text_3_en',
            field=models.CharField(blank=True, default='Easy returns', max_length=100, verbose_name='نص 3 (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_announcement_banner',
            field=models.BooleanField(default=True, help_text='إظهار أو إخفاء شريط الإعلانات أعلى الموقع', verbose_name='إظهار شريط الإعلانات'),
        ),
    ]
