# Generated by Django 5.2.13 on 2026-06-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sitesettings_announcement_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_return_info',
            field=models.TextField(blank=True, default='إرجاع مجاني خلال 30 يوم\nالمنتج يجب أن يكون في حالته الأصلية\nمع جميع الملحقات والفاتورة الأصلية\nاسترداد المبلغ خلال 7-10 أيام عمل\nإمكانية الاستبدال بمنتج آخر', help_text='سطر واحد لكل نقطة', verbose_name='سياسة الإرجاع الافتراضية'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_shipping_info',
            field=models.TextField(blank=True, default='شحن سريع خلال 2-3 أيام عمل داخل عمّان\nشحن خلال 4-5 أيام للمحافظات الأخرى\nإمكانية الشحن الدولي (حسب الوجهة)\nتتبع الشحنة أونلاين\nتغليف آمن ومحكم', help_text='سطر واحد لكل نقطة', verbose_name='معلومات الشحن الافتراضية'),
        ),
    ]
