# Generated by Django 5.2.13 on 2026-06-21 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_pageview_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageview',
            options={},
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['is_bot', 'timestamp'], name='core_pagevi_is_bot_87c543_idx'),
        ),
    ]
