# Generated by Django 5.2.13 on 2026-08-09 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_pageview_status_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pageview',
            new_name='core_pagevi_status__fec093_idx',
            old_name='core_pagevi_status__7a7fcb_idx',
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['session_key', 'timestamp'], name='core_pagevi_session_fbc064_idx'),
        ),
    ]
