# Generated by Django 5.2.4 on 2025-07-11 06:00

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='مبلغ الدفع', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('currency', models.CharField(default='SAR', help_text='رمز العملة', max_length=3, verbose_name='العملة')),
                ('payment_method', models.CharField(choices=[('credit_card', 'بطاقة ائتمان'), ('debit_card', 'بطاقة خصم'), ('bank_transfer', 'تحويل بنكي'), ('cash_on_delivery', 'الدفع عند الاستلام'), ('digital_wallet', 'محفظة إلكترونية'), ('paypal', 'باي بال'), ('apple_pay', 'آبل باي'), ('google_pay', 'جوجل باي'), ('other', 'أخرى')], default='credit_card', help_text='طريقة الدفع المستخدمة', max_length=50, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('authorized', 'مفوض'), ('paid', 'مدفوع'), ('failed', 'فاشل'), ('cancelled', 'ملغي'), ('refunded', 'مسترد'), ('partially_refunded', 'مسترد جزئياً')], default='pending', help_text='حالة الدفع', max_length=20, verbose_name='الحالة')),
                ('payment_gateway', models.CharField(blank=True, help_text='اسم بوابة الدفع المستخدمة', max_length=100, verbose_name='بوابة الدفع')),
                ('gateway_payment_id', models.CharField(blank=True, help_text='معرف عملية الدفع في بوابة الدفع', max_length=255, verbose_name='معرف الدفع في البوابة')),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='استجابة بوابة الدفع الكاملة', verbose_name='استجابة البوابة')),
                ('card_type', models.CharField(blank=True, help_text='نوع البطاقة المستخدمة', max_length=50, verbose_name='نوع البطاقة')),
                ('last_4_digits', models.CharField(blank=True, help_text='آخر 4 أرقام من البطاقة', max_length=4, verbose_name='آخر 4 أرقام')),
                ('card_expiry', models.CharField(blank=True, help_text='تاريخ انتهاء صلاحية البطاقة (MM/YYYY)', max_length=7, verbose_name='تاريخ انتهاء البطاقة')),
                ('billing_address', models.TextField(blank=True, help_text='العنوان المستخدم للفواتير', verbose_name='عنوان الفواتير')),
                ('description', models.TextField(blank=True, help_text='وصف عملية الدفع', verbose_name='الوصف')),
                ('notes', models.TextField(blank=True, help_text='ملاحظات داخلية', verbose_name='الملاحظات')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='عنوان IP للمستخدم عند الدفع', null=True, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('paid_at', models.DateTimeField(blank=True, help_text='تاريخ اكتمال الدفع', null=True, verbose_name='تاريخ الدفع')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='orders.order', verbose_name='الطلب')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'عملية دفع',
                'verbose_name_plural': 'عمليات الدفع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(help_text='رقم مرجع فريد للمعاملة', max_length=100, unique=True, verbose_name='رقم المرجع')),
                ('amount', models.DecimalField(decimal_places=2, help_text='مبلغ المعاملة', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('currency', models.CharField(default='SAR', help_text='رمز العملة (مثل SAR أو USD)', max_length=3, verbose_name='العملة')),
                ('fees', models.DecimalField(decimal_places=2, default=0, help_text='رسوم المعاملة', max_digits=12, verbose_name='الرسوم')),
                ('transaction_type', models.CharField(choices=[('payment', 'دفع'), ('refund', 'استرداد'), ('deposit', 'إيداع'), ('withdrawal', 'سحب'), ('transfer', 'تحويل'), ('adjustment', 'تسوية'), ('fee', 'رسوم'), ('other', 'أخرى')], default='payment', help_text='نوع المعاملة المالية', max_length=20, verbose_name='نوع المعاملة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('completed', 'مكتملة'), ('failed', 'فاشلة'), ('cancelled', 'ملغية'), ('reversed', 'معكوسة')], default='pending', help_text='حالة المعاملة المالية', max_length=20, verbose_name='الحالة')),
                ('payment_gateway', models.CharField(blank=True, help_text='اسم بوابة الدفع المستخدمة', max_length=100, verbose_name='بوابة الدفع')),
                ('payment_method', models.CharField(blank=True, help_text='طريقة الدفع المستخدمة', max_length=100, verbose_name='طريقة الدفع')),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='معرف المعاملة في بوابة الدفع الخارجية', max_length=255, verbose_name='معرف المعاملة في البوابة')),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='استجابة بوابة الدفع الكاملة', verbose_name='استجابة البوابة')),
                ('description', models.TextField(blank=True, help_text='وصف المعاملة', verbose_name='الوصف')),
                ('notes', models.TextField(blank=True, help_text='ملاحظات داخلية حول المعاملة', verbose_name='الملاحظات')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='بيانات إضافية للمعاملة', verbose_name='بيانات وصفية')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='عنوان IP للمستخدم عند إجراء المعاملة', null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, help_text='معلومات متصفح المستخدم', verbose_name='متصفح المستخدم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('completed_at', models.DateTimeField(blank=True, help_text='تاريخ إكمال المعاملة', null=True, verbose_name='تاريخ الإكمال')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.order', verbose_name='الطلب')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'معاملة مالية',
                'verbose_name_plural': 'معاملات مالية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='مبلغ الاسترداد', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('currency', models.CharField(default='SAR', help_text='رمز العملة', max_length=3, verbose_name='العملة')),
                ('reason', models.CharField(choices=[('customer_request', 'طلب العميل'), ('duplicate_payment', 'دفع مكرر'), ('fraudulent', 'معاملة احتيالية'), ('order_cancelled', 'إلغاء الطلب'), ('item_unavailable', 'المنتج غير متوفر'), ('shipping_issue', 'مشكلة في الشحن'), ('quality_issue', 'مشكلة في الجودة'), ('wrong_item', 'منتج خاطئ'), ('other', 'أخرى')], default='customer_request', help_text='سبب طلب الاسترداد', max_length=50, verbose_name='سبب الاسترداد')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فاشل'), ('cancelled', 'ملغي')], default='pending', help_text='حالة الاسترداد', max_length=20, verbose_name='الحالة')),
                ('refund_gateway', models.CharField(blank=True, help_text='اسم بوابة الدفع المستخدمة للاسترداد', max_length=100, verbose_name='بوابة الاسترداد')),
                ('gateway_refund_id', models.CharField(blank=True, help_text='معرف عملية الاسترداد في بوابة الدفع', max_length=255, verbose_name='معرف الاسترداد في البوابة')),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='استجابة بوابة الدفع الكاملة للاسترداد', verbose_name='استجابة البوابة')),
                ('notes', models.TextField(blank=True, help_text='ملاحظات داخلية حول الاسترداد', verbose_name='الملاحظات')),
                ('customer_notes', models.TextField(blank=True, help_text='ملاحظات العميل حول سبب الاسترداد', verbose_name='ملاحظات العميل')),
                ('admin_notes', models.TextField(blank=True, help_text='ملاحظات المدير حول الاسترداد', verbose_name='ملاحظات الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('completed_at', models.DateTimeField(blank=True, help_text='تاريخ اكتمال الاسترداد', null=True, verbose_name='تاريخ الإكمال')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='orders.order', verbose_name='الطلب')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payment.payment', verbose_name='عملية الدفع')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL, verbose_name='تمت معالجته بواسطة')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_refunds', to=settings.AUTH_USER_MODEL, verbose_name='طلب بواسطة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund', to='payment.transaction', verbose_name='المعاملة')),
            ],
            options={
                'verbose_name': 'عملية استرداد',
                'verbose_name_plural': 'عمليات الاسترداد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='payment.transaction', verbose_name='المعاملة'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_number'], name='payment_tra_referen_a5c542_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type'], name='payment_tra_user_id_185e83_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['order'], name='payment_tra_order_i_c6a3d5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='payment_tra_status_373de7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='payment_tra_created_0d0f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_gateway'], name='payment_tra_payment_b81597_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment'], name='payment_ref_payment_3e571e_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['order'], name='payment_ref_order_i_c7f601_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['user'], name='payment_ref_user_id_ded9e7_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status'], name='payment_ref_status_a5dd15_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['created_at'], name='payment_ref_created_4a5a64_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['completed_at'], name='payment_ref_complet_3aa17a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='payment_pay_order_i_211f02_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user'], name='payment_pay_user_id_e01707_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payment_pay_status_124d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='payment_pay_payment_7d17d2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payment_pay_created_671024_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_at'], name='payment_pay_paid_at_078a12_idx'),
        ),
    ]
