# Generated by Django 5.2.13 on 2026-05-01 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='تفعيل الشات بوت')),
                ('provider', models.CharField(choices=[('openrouter', 'OpenRouter'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google Gemini')], default='openrouter', max_length=20, verbose_name='مزود الذكاء الاصطناعي')),
                ('api_key', models.CharField(blank=True, default='', max_length=500, verbose_name='مفتاح API')),
                ('model_name', models.CharField(default='openrouter/free', max_length=200, verbose_name='اسم النموذج')),
                ('temperature', models.DecimalField(decimal_places=2, default=0.7, max_digits=3, verbose_name='درجة الإبداع')),
                ('max_tokens', models.PositiveIntegerField(default=1024, verbose_name='الحد الأقصى للتوكنات')),
                ('primary_color', models.CharField(default='#1e88e5', max_length=7, verbose_name='اللون الرئيسي')),
                ('secondary_color', models.CharField(default='#ffffff', max_length=7, verbose_name='اللون الثانوي')),
                ('position', models.CharField(choices=[('bottom-right', 'أسفل اليمين'), ('bottom-left', 'أسفل اليسار')], default='bottom-right', max_length=20, verbose_name='موقع الفقاعة')),
                ('bubble_size', models.CharField(choices=[('small', 'صغير'), ('medium', 'متوسط'), ('large', 'كبير')], default='medium', max_length=10, verbose_name='حجم الفقاعة')),
                ('show_on_mobile', models.BooleanField(default=True, verbose_name='إظهار على الجوال')),
                ('welcome_message_ar', models.TextField(default='مرحباً! كيف يمكنني مساعدتك اليوم؟', verbose_name='رسالة الترحيب (عربي)')),
                ('welcome_message_en', models.TextField(default='Hello! How can I help you today?', verbose_name='رسالة الترحيب (إنجليزي)')),
                ('bot_name_ar', models.CharField(default='مساعد ESCO', max_length=50, verbose_name='اسم البوت (عربي)')),
                ('bot_name_en', models.CharField(default='ESCO Assistant', max_length=50, verbose_name='اسم البوت (إنجليزي)')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='chatbot/', verbose_name='صورة البوت')),
                ('system_prompt_ar', models.TextField(blank=True, default='', verbose_name='تعليمات النظام (عربي)')),
                ('system_prompt_en', models.TextField(blank=True, default='', verbose_name='تعليمات النظام (إنجليزي)')),
                ('max_history_messages', models.PositiveIntegerField(default=10, verbose_name='عدد الرسائل في السياق')),
                ('enable_product_search', models.BooleanField(default=True, verbose_name='تفعيل البحث في المنتجات')),
                ('enable_blog_search', models.BooleanField(default=True, verbose_name='تفعيل البحث في المدونة')),
                ('enable_comparison', models.BooleanField(default=True, verbose_name='تفعيل مقارنة المنتجات')),
                ('enable_suggestions', models.BooleanField(default=True, verbose_name='تفعيل الاقتراحات الذكية')),
                ('max_messages_per_session', models.PositiveIntegerField(default=50, verbose_name='الحد الأقصى لرسائل الجلسة')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=10, verbose_name='الحد الأقصى للرسائل بالدقيقة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات الشات بوت',
                'verbose_name_plural': 'إعدادات الشات بوت',
            },
        ),
        migrations.CreateModel(
            name='CustomQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ar', models.CharField(max_length=500, verbose_name='السؤال (عربي)')),
                ('question_en', models.CharField(blank=True, default='', max_length=500, verbose_name='السؤال (إنجليزي)')),
                ('answer_ar', models.TextField(verbose_name='الإجابة (عربي)')),
                ('answer_en', models.TextField(blank=True, default='', verbose_name='الإجابة (إنجليزي)')),
                ('keywords', models.CharField(blank=True, default='', help_text='كلمات مفتاحية مفصولة بفواصل للمطابقة', max_length=500, verbose_name='كلمات مفتاحية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('priority', models.PositiveIntegerField(default=0, help_text='رقم أعلى = أولوية أعلى', verbose_name='الأولوية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سؤال وجواب مخصص',
                'verbose_name_plural': 'أسئلة وأجوبة مخصصة',
                'ordering': ['-priority', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SuggestedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ar', models.CharField(max_length=200, verbose_name='النص (عربي)')),
                ('text_en', models.CharField(blank=True, default='', max_length=200, verbose_name='النص (إنجليزي)')),
                ('icon', models.CharField(blank=True, default='fas fa-question-circle', max_length=50, verbose_name='أيقونة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'سؤال مقترح',
                'verbose_name_plural': 'الأسئلة المقترحة',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, verbose_name='مفتاح الجلسة')),
                ('language', models.CharField(default='ar', max_length=5, verbose_name='اللغة')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='بدأت في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('page_url', models.URLField(blank=True, default='', max_length=500, verbose_name='صفحة المحادثة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_conversations', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'محادثة',
                'verbose_name_plural': 'المحادثات',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'المستخدم'), ('assistant', 'المساعد')], max_length=10, verbose_name='الدور')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('rich_content', models.JSONField(blank=True, default=dict, verbose_name='محتوى غني')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='التوكنات المستخدمة')),
                ('response_time_ms', models.PositiveIntegerField(default=0, verbose_name='وقت الاستجابة (مللي ثانية)')),
                ('provider_used', models.CharField(blank=True, default='', max_length=50, verbose_name='المزود')),
                ('model_used', models.CharField(blank=True, default='', max_length=200, verbose_name='النموذج')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئت في')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation', verbose_name='المحادثة')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['session_key'], name='chatbot_con_session_b87ccc_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-updated_at'], name='chatbot_con_updated_ef879c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chatbot_mes_convers_b353f0_idx'),
        ),
    ]
