# Generated by Django 5.2.13 on 2026-05-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotsettings',
            name='avatar_icon',
            field=models.CharField(blank=True, default='fas fa-robot', max_length=50, verbose_name='أيقونة البوت'),
        ),
    ]
