# Generated by Django 5.2.13 on 2026-05-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_add_avatar_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotsettings',
            name='avatar_icon_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='لون أيقونة البوت'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='bubble_bg_color',
            field=models.CharField(blank=True, default='#1e88e5', max_length=7, verbose_name='لون خلفية الفقاعة'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='bubble_icon',
            field=models.CharField(blank=True, default='fas fa-comments', max_length=50, verbose_name='أيقونة الفقاعة'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='bubble_icon_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='لون أيقونة الفقاعة'),
        ),
    ]
