# Generated by Django 5.2.13 on 2026-05-01 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_add_icon_color_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='رقم الهاتف')),
                ('customer_address', models.TextField(blank=True, default='', verbose_name='العنوان')),
                ('expected_date', models.CharField(blank=True, default='', max_length=100, verbose_name='التاريخ المتوقع للاستلام')),
                ('product_interest', models.TextField(blank=True, default='', verbose_name='المنتج / الاهتمام')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات العميل')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('contacted', 'تم التواصل'), ('in_progress', 'قيد المتابعة'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('language', models.CharField(default='ar', max_length=5, verbose_name='اللغة')),
                ('session_key', models.CharField(blank=True, default='', max_length=64, verbose_name='مفتاح الجلسة')),
                ('page_url', models.URLField(blank=True, default='', max_length=500, verbose_name='صفحة المحادثة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='مسؤول المتابعة')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_requests', to='chatbot.conversation', verbose_name='المحادثة')),
            ],
            options={
                'verbose_name': 'طلب عميل',
                'verbose_name_plural': 'طلبات العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='التعليق')),
                ('old_status', models.CharField(blank=True, default='', max_length=20, verbose_name='الحالة السابقة')),
                ('new_status', models.CharField(blank=True, default='', max_length=20, verbose_name='الحالة الجديدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعليق')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_comments', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='chatbot.leadrequest', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'التعليقات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='leadrequest',
            index=models.Index(fields=['status', '-created_at'], name='chatbot_lea_status_a5da00_idx'),
        ),
        migrations.AddIndex(
            model_name='leadrequest',
            index=models.Index(fields=['-created_at'], name='chatbot_lea_created_5c046d_idx'),
        ),
    ]
