# Generated by Django 5.2.13 on 2026-05-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_add_lead_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotsettings',
            name='hide_out_of_stock',
            field=models.BooleanField(default=False, verbose_name='إخفاء المنتجات غير المتوفرة'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='hide_products_without_price',
            field=models.BooleanField(default=True, verbose_name='إخفاء المنتجات بدون سعر'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='product_sort_order',
            field=models.CharField(choices=[('newest', 'الأحدث أولاً'), ('price_low', 'السعر: من الأقل للأعلى'), ('price_high', 'السعر: من الأعلى للأقل'), ('name', 'الاسم أبجدياً')], default='newest', max_length=20, verbose_name='ترتيب المنتجات'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='product_status_filter',
            field=models.CharField(choices=[('published_only', 'المنشورة فقط'), ('published_and_draft', 'المنشورة والمسودة'), ('all', 'الكل')], default='published_only', max_length=20, verbose_name='فلتر حالة المنتج'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='show_categories_in_response',
            field=models.BooleanField(default=True, verbose_name='عرض الأقسام في الرد'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='show_price_in_response',
            field=models.BooleanField(default=True, verbose_name='عرض السعر في الرد'),
        ),
    ]
