# Generated by Django 5.2.13 on 2026-05-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_product_display_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotsettings',
            name='auto_play_voice',
            field=models.BooleanField(default=False, verbose_name='تشغيل الصوت تلقائياً'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='enable_voice_input',
            field=models.BooleanField(default=False, verbose_name='تفعيل الإدخال الصوتي'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='enable_voice_output',
            field=models.BooleanField(default=False, verbose_name='تفعيل الرد الصوتي'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='voice_api_key',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='مفتاح API للصوت'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='voice_id',
            field=models.CharField(blank=True, default='', help_text='معرّف الصوت لدى المزود (مثل: alloy لـ OpenAI أو معرّف ElevenLabs)', max_length=200, verbose_name='معرّف الصوت'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='voice_language',
            field=models.CharField(choices=[('ar-SA', 'العربية (السعودية)'), ('ar-JO', 'العربية (الأردن)'), ('ar-EG', 'العربية (مصر)'), ('ar-AE', 'العربية (الإمارات)'), ('en-US', 'الإنجليزية (أمريكا)'), ('en-GB', 'الإنجليزية (بريطانيا)')], default='ar-SA', max_length=10, verbose_name='لغة الصوت'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='voice_provider',
            field=models.CharField(choices=[('browser', 'متصفح (مجاني)'), ('openai', 'OpenAI'), ('elevenlabs', 'ElevenLabs'), ('google', 'Google Cloud'), ('azure', 'Azure')], default='browser', max_length=20, verbose_name='مزود الصوت'),
        ),
    ]
