# Generated by Django 5.2.13 on 2026-05-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_voice_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotsettings',
            name='custom_voice_auth_header',
            field=models.CharField(blank=True, default='Authorization', help_text='مثال: Authorization أو x-api-key أو xi-api-key', max_length=100, verbose_name='اسم هيدر المصادقة'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='custom_voice_auth_prefix',
            field=models.CharField(blank=True, default='Bearer', help_text='مثال: Bearer أو Token أو اتركه فارغاً', max_length=50, verbose_name='بادئة المصادقة'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='custom_voice_response_path',
            field=models.CharField(blank=True, default='text', help_text='مسار JSON للنص المُحوَّل (مثال: text أو result.transcript أو data.text)', max_length=200, verbose_name='مسار النص في الرد'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='custom_voice_stt_field',
            field=models.CharField(blank=True, default='file', help_text='اسم الحقل في multipart/form-data (مثال: file أو audio)', max_length=50, verbose_name='اسم حقل الملف الصوتي'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='custom_voice_stt_url',
            field=models.URLField(blank=True, default='', help_text='مثال: https://api.lahajati.ai/v1/stt', max_length=500, verbose_name='رابط API للتعرف على الصوت (STT)'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='custom_voice_tts_body',
            field=models.TextField(blank=True, default='', help_text='JSON template — استخدم {text} و {voice_id} و {language} كمتغيرات', verbose_name='قالب Body للنطق (JSON)'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='custom_voice_tts_url',
            field=models.URLField(blank=True, default='', help_text='مثال: https://api.lahajati.ai/v1/tts', max_length=500, verbose_name='رابط API للنطق (TTS)'),
        ),
        migrations.AlterField(
            model_name='chatbotsettings',
            name='voice_provider',
            field=models.CharField(choices=[('browser', 'متصفح (مجاني)'), ('openai', 'OpenAI'), ('elevenlabs', 'ElevenLabs'), ('google', 'Google Cloud'), ('azure', 'Azure'), ('custom', 'مخصص (أي منصة)')], default='browser', max_length=20, verbose_name='مزود الصوت'),
        ),
    ]
