# Generated by Django 5.2.13 on 2026-05-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_custom_voice_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotsettings',
            name='voice_provider',
            field=models.CharField(choices=[('free', 'مجاني (يدعم العربية)'), ('browser', 'متصفح فقط'), ('openai', 'OpenAI'), ('elevenlabs', 'ElevenLabs'), ('google', 'Google Cloud'), ('azure', 'Azure'), ('custom', 'مخصص (أي منصة)')], default='browser', max_length=20, verbose_name='مزود الصوت'),
        ),
    ]
