# Generated by Django 5.2.13 on 2026-05-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_free_voice_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotsettings',
            name='enable_voice_agent',
            field=models.BooleanField(default=False, verbose_name='تفعيل الوكيل الصوتي'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='voice_agent_api_key',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='مفتاح API للوكيل الصوتي'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='voice_agent_button_color',
            field=models.CharField(default='#4caf50', max_length=7, verbose_name='لون زر الوكيل'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='voice_agent_button_icon',
            field=models.CharField(default='fas fa-phone-alt', max_length=50, verbose_name='أيقونة زر الوكيل'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='voice_agent_button_position',
            field=models.CharField(choices=[('bottom-right', 'أسفل اليمين'), ('bottom-left', 'أسفل اليسار')], default='bottom-left', max_length=20, verbose_name='موقع زر الوكيل'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='voice_agent_custom_api_url',
            field=models.URLField(blank=True, default='', help_text='رابط REST API لبدء/إنهاء المكالمة', max_length=500, verbose_name='رابط API للوكيل'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='voice_agent_custom_auth_header',
            field=models.CharField(blank=True, default='Authorization', max_length=100, verbose_name='هيدر المصادقة'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='voice_agent_custom_auth_prefix',
            field=models.CharField(blank=True, default='Bearer', max_length=50, verbose_name='بادئة المصادقة'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='voice_agent_custom_ws_url',
            field=models.URLField(blank=True, default='', help_text='رابط WebSocket للاتصال المباشر بالوكيل الصوتي', max_length=500, verbose_name='رابط WebSocket'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='voice_agent_embed_code',
            field=models.TextField(blank=True, default='', help_text='كود HTML/JS من المزود لتضمينه مباشرة (اختياري — يُستخدم بدلاً من SDK)', verbose_name='كود التضمين (Embed)'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='voice_agent_extra_config',
            field=models.JSONField(blank=True, default=dict, help_text='إعدادات إضافية بصيغة JSON تُمرر للمزود', verbose_name='إعدادات إضافية (JSON)'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='voice_agent_id',
            field=models.CharField(blank=True, default='', help_text='معرّف الوكيل/المساعد لدى المزود (Agent ID أو Assistant ID)', max_length=200, verbose_name='معرّف الوكيل الصوتي'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='voice_agent_label_ar',
            field=models.CharField(blank=True, default='تحدث معنا', max_length=50, verbose_name='نص الزر (عربي)'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='voice_agent_label_en',
            field=models.CharField(blank=True, default='Talk to us', max_length=50, verbose_name='نص الزر (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='voice_agent_phone_number',
            field=models.CharField(blank=True, default='', help_text='رقم الهاتف المربوط بالوكيل (اختياري)', max_length=30, verbose_name='رقم هاتف الوكيل'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='voice_agent_provider',
            field=models.CharField(choices=[('vapi', 'Vapi.ai'), ('bland', 'Bland.ai'), ('retell', 'Retell.ai'), ('voiceflow', 'Voiceflow'), ('livekit', 'LiveKit'), ('custom_agent', 'مخصص (أي منصة)')], default='vapi', max_length=20, verbose_name='مزود الوكيل الصوتي'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='voice_agent_trigger',
            field=models.CharField(choices=[('floating_button', 'زر عائم مستقل'), ('inside_chatbot', 'داخل نافذة الشات'), ('replace_chatbot', 'يحل محل الشات بوت')], default='floating_button', max_length=20, verbose_name='طريقة تشغيل الوكيل'),
        ),
    ]
