# Generated by Django 5.0.1 on 2025-05-28 17:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('notification_type', models.CharField(choices=[('info', 'معلومات'), ('success', 'نجاح'), ('warning', 'تحذير'), ('error', 'خطأ')], default='info', max_length=10, verbose_name='نوع الإشعار')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='نوع الكائن المرتبط')),
                ('related_object_id', models.CharField(blank=True, max_length=100, verbose_name='معرف الكائن المرتبط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار لوحة التحكم',
                'verbose_name_plural': 'إشعارات لوحة التحكم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعيين')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_product_reviews', to=settings.AUTH_USER_MODEL, verbose_name='تم التعيين بواسطة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='products.product', verbose_name='المنتج')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review_assignments', to=settings.AUTH_USER_MODEL, verbose_name='المراجع')),
            ],
            options={
                'verbose_name': 'تعيين مراجعة المنتج',
                'verbose_name_plural': 'تعيينات مراجعة المنتج',
                'unique_together': {('product', 'reviewer')},
            },
        ),
    ]
