# Generated by Django 5.2.4 on 2025-07-11 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviewassignment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='products.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='productreviewassignment',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review_assignments', to=settings.AUTH_USER_MODEL, verbose_name='المراجع'),
        ),
        migrations.AddIndex(
            model_name='dashboardnotification',
            index=models.Index(fields=['user', 'is_read'], name='dashboard_d_user_id_561e39_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardnotification',
            index=models.Index(fields=['user', 'created_at'], name='dashboard_d_user_id_596f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardnotification',
            index=models.Index(fields=['notification_type'], name='dashboard_d_notific_4bf483_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardnotification',
            index=models.Index(fields=['related_object_type', 'related_object_id'], name='dashboard_d_related_7e918e_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardnotification',
            index=models.Index(fields=['expires_at'], name='dashboard_d_expires_36187f_idx'),
        ),
        migrations.AddIndex(
            model_name='productreviewassignment',
            index=models.Index(fields=['reviewer', 'is_completed'], name='dashboard_p_reviewe_43cd0a_idx'),
        ),
        migrations.AddIndex(
            model_name='productreviewassignment',
            index=models.Index(fields=['product', 'is_completed'], name='dashboard_p_product_cdc34c_idx'),
        ),
        migrations.AddIndex(
            model_name='productreviewassignment',
            index=models.Index(fields=['assigned_at'], name='dashboard_p_assigne_2a898d_idx'),
        ),
        migrations.AddIndex(
            model_name='productreviewassignment',
            index=models.Index(fields=['due_date'], name='dashboard_p_due_dat_3e409b_idx'),
        ),
        migrations.AddIndex(
            model_name='productreviewassignment',
            index=models.Index(fields=['priority'], name='dashboard_p_priorit_d08ad4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productreviewassignment',
            unique_together={('product', 'reviewer')},
        ),
    ]
