# Generated by Django 5.2.13 on 2026-04-24 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
        ('products', '0007_add_product_notes_and_activity_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'إنشاء'), ('price_changed', 'تغيير السعر'), ('stock_changed', 'تغيير المخزون'), ('status_changed', 'تغيير الحالة'), ('updated', 'تحديث')], max_length=30, verbose_name='الإجراء')),
                ('field_name', models.CharField(blank=True, max_length=50, verbose_name='الحقل')),
                ('old_value', models.CharField(blank=True, max_length=255, verbose_name='القيمة القديمة')),
                ('new_value', models.CharField(blank=True, max_length=255, verbose_name='القيمة الجديدة')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='التاريخ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='products.product', verbose_name='المنتج')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل نشاط المنتج',
                'verbose_name_plural': 'سجلات نشاط المنتجات',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProductNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('note_type', models.CharField(choices=[('general', 'ملاحظة عامة'), ('price', 'تسعير'), ('stock', 'مخزون'), ('quality', 'جودة'), ('supplier', 'مورد'), ('todo', 'مهمة')], default='general', max_length=20, verbose_name='نوع الملاحظة')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم الحل')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notes', to='products.product', verbose_name='المنتج')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملاحظة منتج',
                'verbose_name_plural': 'ملاحظات المنتجات',
                'ordering': ['-created_at'],
            },
        ),
    ]
