# Generated by Django 5.2.13 on 2026-04-24 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_add_product_notes_and_activity_log'),
        ('products', '0007_add_product_notes_and_activity_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productactivitylog',
            name='action',
            field=models.CharField(choices=[('created', 'إنشاء'), ('price_changed', 'تغيير السعر'), ('stock_changed', 'تغيير المخزون'), ('status_changed', 'تغيير الحالة'), ('updated', 'تحديث')], db_index=True, max_length=30, verbose_name='الإجراء'),
        ),
        migrations.AddIndex(
            model_name='productactivitylog',
            index=models.Index(fields=['action', '-timestamp'], name='dashboard_p_action_c260bf_idx'),
        ),
        migrations.AddIndex(
            model_name='productactivitylog',
            index=models.Index(fields=['product', '-timestamp'], name='dashboard_p_product_3ceaa6_idx'),
        ),
        migrations.AddIndex(
            model_name='productnote',
            index=models.Index(fields=['product', '-created_at'], name='dashboard_p_product_6f9767_idx'),
        ),
        migrations.AddIndex(
            model_name='productnote',
            index=models.Index(fields=['is_resolved', '-created_at'], name='dashboard_p_is_reso_cfa41e_idx'),
        ),
    ]
