# Generated by Django 5.2.1 on 2025-05-31 11:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='البريد الإلكتروني للمستخدم', max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="رقم الهاتف يجب أن يكون في الصيغة: '+999999999'. حتى 15 رقم مسموح.", regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم الهاتف')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='الصورة الشخصية')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(blank=True, choices=[('M', 'ذكر'), ('F', 'أنثى'), ('O', 'آخر')], max_length=1, verbose_name='الجنس')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='الدولة')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='الرمز البريدي')),
                ('is_verified', models.BooleanField(default=False, help_text='هل تم تأكيد البريد الإلكتروني؟', verbose_name='موثق')),
                ('is_product_reviewer', models.BooleanField(default=False, help_text='يمكن للمستخدم مراجعة المنتجات في لوحة التحكم', verbose_name='مراجع منتجات')),
                ('accept_marketing', models.BooleanField(default=False, help_text='هل يوافق على تلقي رسائل تسويقية؟', verbose_name='أوافق على التسويق')),
                ('language', models.CharField(choices=[('ar', 'العربية'), ('en', 'الإنجليزية')], default='ar', max_length=10, verbose_name='اللغة المفضلة')),
                ('timezone', models.CharField(blank=True, default='Asia/Riyadh', max_length=50, verbose_name='المنطقة الزمنية')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='آخر نشاط')),
                ('total_orders', models.PositiveIntegerField(default=0, editable=False, verbose_name='إجمالي الطلبات')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='إجمالي المبلغ المنفق')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50, verbose_name='نوع النشاط')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكائن')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='نوع المحتوى')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التوقيت')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'نشاط المستخدم',
                'verbose_name_plural': 'أنشطة المستخدمين',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='مثل: المنزل، العمل، إلخ', max_length=100, verbose_name='تسمية العنوان')),
                ('type', models.CharField(choices=[('home', 'المنزل'), ('work', 'العمل'), ('other', 'آخر')], default='home', max_length=10, verbose_name='نوع العنوان')),
                ('first_name', models.CharField(max_length=50, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=50, verbose_name='اسم العائلة')),
                ('address_line_1', models.CharField(max_length=200, verbose_name='سطر العنوان الأول')),
                ('address_line_2', models.CharField(blank=True, max_length=200, verbose_name='سطر العنوان الثاني')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='الولاية/المنطقة')),
                ('postal_code', models.CharField(max_length=20, verbose_name='الرمز البريدي')),
                ('country', models.CharField(max_length=100, verbose_name='الدولة')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('is_default', models.BooleanField(default=False, verbose_name='العنوان الافتراضي')),
                ('is_billing_default', models.BooleanField(default=False, verbose_name='عنوان الفوترة الافتراضي')),
                ('is_shipping_default', models.BooleanField(default=False, verbose_name='عنوان الشحن الافتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'عنوان مستخدم',
                'verbose_name_plural': 'عناوين المستخدمين',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الشخصي')),
                ('twitter', models.CharField(blank=True, max_length=100, verbose_name='تويتر')),
                ('facebook', models.CharField(blank=True, max_length=100, verbose_name='فيسبوك')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='انستغرام')),
                ('linkedin', models.CharField(blank=True, max_length=100, verbose_name='لينكد إن')),
                ('bio', models.TextField(blank=True, help_text='نبذة مختصرة عن المستخدم', max_length=500, verbose_name='نبذة شخصية')),
                ('interests', models.TextField(blank=True, help_text='اهتمامات المستخدم مفصولة بفواصل', verbose_name='الاهتمامات')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='المهنة')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='الشركة')),
                ('notification_preferences', models.JSONField(blank=True, default=dict, verbose_name='تفضيلات الإشعارات')),
                ('privacy_settings', models.JSONField(blank=True, default=dict, verbose_name='إعدادات الخصوصية')),
                ('identity_verified', models.BooleanField(default=False, verbose_name='موثق الهوية')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='موثق الهاتف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف شخصي',
                'verbose_name_plural': 'الملفات الشخصية',
            },
        ),
    ]
