# Generated by Django 5.2.1 on 2025-06-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_password_reset_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='object_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف الكائن'),
        ),
    ]
