"""Country lookup: English GeoIP name -> Arabic name + flag emoji + ISO code.

Flag emojis use Unicode regional indicator pairs derived from the ISO 3166-1
alpha-2 code. Browsers render them as country flags on most platforms.
"""

# (Arabic name, ISO alpha-2 code)
_COUNTRY_AR = {
    # Arab League
    "Jordan": ("الأردن", "JO"),
    "Hashemite Kingdom of Jordan": ("الأردن", "JO"),
    "Saudi Arabia": ("السعودية", "SA"),
    "United Arab Emirates": ("الإمارات", "AE"),
    "Kuwait": ("الكويت", "KW"),
    "Qatar": ("قطر", "QA"),
    "Bahrain": ("البحرين", "BH"),
    "Oman": ("عُمان", "OM"),
    "Yemen": ("اليمن", "YE"),
    "Iraq": ("العراق", "IQ"),
    "Syria": ("سوريا", "SY"),
    "Lebanon": ("لبنان", "LB"),
    "Palestine": ("فلسطين", "PS"),
    "State of Palestine": ("فلسطين", "PS"),
    "Egypt": ("مصر", "EG"),
    "Libya": ("ليبيا", "LY"),
    "Tunisia": ("تونس", "TN"),
    "Algeria": ("الجزائر", "DZ"),
    "Morocco": ("المغرب", "MA"),
    "Mauritania": ("موريتانيا", "MR"),
    "Sudan": ("السودان", "SD"),
    "Somalia": ("الصومال", "SO"),
    "Djibouti": ("جيبوتي", "DJ"),
    "Comoros": ("جزر القمر", "KM"),

    # Major economies
    "United States": ("الولايات المتحدة", "US"),
    "United Kingdom": ("المملكة المتحدة", "GB"),
    "Germany": ("ألمانيا", "DE"),
    "France": ("فرنسا", "FR"),
    "Italy": ("إيطاليا", "IT"),
    "Spain": ("إسبانيا", "ES"),
    "Portugal": ("البرتغال", "PT"),
    "Netherlands": ("هولندا", "NL"),
    "Belgium": ("بلجيكا", "BE"),
    "Switzerland": ("سويسرا", "CH"),
    "Austria": ("النمسا", "AT"),
    "Sweden": ("السويد", "SE"),
    "Norway": ("النرويج", "NO"),
    "Denmark": ("الدنمارك", "DK"),
    "Finland": ("فنلندا", "FI"),
    "Ireland": ("أيرلندا", "IE"),
    "Greece": ("اليونان", "GR"),
    "Poland": ("بولندا", "PL"),
    "Czechia": ("التشيك", "CZ"),
    "Czech Republic": ("التشيك", "CZ"),
    "Romania": ("رومانيا", "RO"),
    "Hungary": ("المجر", "HU"),
    "Ukraine": ("أوكرانيا", "UA"),
    "Russia": ("روسيا", "RU"),
    "Russian Federation": ("روسيا", "RU"),
    "Turkey": ("تركيا", "TR"),
    "Türkiye": ("تركيا", "TR"),
    "Israel": ("إسرائيل", "IL"),
    "Iran": ("إيران", "IR"),
    "Pakistan": ("باكستان", "PK"),
    "India": ("الهند", "IN"),
    "China": ("الصين", "CN"),
    "Hong Kong": ("هونغ كونغ", "HK"),
    "Japan": ("اليابان", "JP"),
    "South Korea": ("كوريا الجنوبية", "KR"),
    "Korea, Republic of": ("كوريا الجنوبية", "KR"),
    "Singapore": ("سنغافورة", "SG"),
    "Malaysia": ("ماليزيا", "MY"),
    "Indonesia": ("إندونيسيا", "ID"),
    "Thailand": ("تايلاند", "TH"),
    "Vietnam": ("فيتنام", "VN"),
    "Philippines": ("الفلبين", "PH"),
    "Australia": ("أستراليا", "AU"),
    "New Zealand": ("نيوزيلندا", "NZ"),
    "Canada": ("كندا", "CA"),
    "Mexico": ("المكسيك", "MX"),
    "Brazil": ("البرازيل", "BR"),
    "Argentina": ("الأرجنتين", "AR"),
    "Chile": ("تشيلي", "CL"),
    "Colombia": ("كولومبيا", "CO"),
    "Peru": ("بيرو", "PE"),
    "Venezuela": ("فنزويلا", "VE"),
    "South Africa": ("جنوب أفريقيا", "ZA"),
    "Nigeria": ("نيجيريا", "NG"),
    "Kenya": ("كينيا", "KE"),
    "Ethiopia": ("إثيوبيا", "ET"),
    "Ghana": ("غانا", "GH"),
    "Tanzania": ("تنزانيا", "TZ"),
    "Afghanistan": ("أفغانستان", "AF"),
    "Bangladesh": ("بنغلاديش", "BD"),
    "Sri Lanka": ("سريلانكا", "LK"),
    "Nepal": ("نيبال", "NP"),
    "Azerbaijan": ("أذربيجان", "AZ"),
    "Armenia": ("أرمينيا", "AM"),
    "Georgia": ("جورجيا", "GE"),
    "Kazakhstan": ("كازاخستان", "KZ"),
    "Uzbekistan": ("أوزبكستان", "UZ"),
    "Turkmenistan": ("تركمانستان", "TM"),
}


# Cities encountered in the wild — extend as needed
_CITY_AR = {
    "Frankfurt am Main": "فرانكفورت",
    "Dubai": "دبي",
    "San Mateo": "سان ماتيو",
    "Beijing": "بكين",
    "Berazategui": "بيراساتيغوي",
    "Ashburn": "آشبيرن",
    "Newark": "نيوارك",
    "Amman": "عمّان",
    "Irbid": "إربد",
    "Zarqa": "الزرقاء",
    "Aqaba": "العقبة",
    "Riyadh": "الرياض",
    "Jeddah": "جدة",
    "Mecca": "مكة المكرمة",
    "Medina": "المدينة المنورة",
    "Dammam": "الدمام",
    "Abu Dhabi": "أبو ظبي",
    "Sharjah": "الشارقة",
    "Doha": "الدوحة",
    "Kuwait City": "مدينة الكويت",
    "Manama": "المنامة",
    "Muscat": "مسقط",
    "Cairo": "القاهرة",
    "Alexandria": "الإسكندرية",
    "Beirut": "بيروت",
    "Damascus": "دمشق",
    "Baghdad": "بغداد",
    "Basra": "البصرة",
    "Erbil": "أربيل",
    "Sanaa": "صنعاء",
    "Khartoum": "الخرطوم",
    "Tripoli": "طرابلس",
    "Tunis": "تونس",
    "Algiers": "الجزائر",
    "Casablanca": "الدار البيضاء",
    "Rabat": "الرباط",
    "Marrakesh": "مراكش",
    "Istanbul": "إسطنبول",
    "Ankara": "أنقرة",
    "London": "لندن",
    "Paris": "باريس",
    "Berlin": "برلين",
    "Munich": "ميونخ",
    "Madrid": "مدريد",
    "Barcelona": "برشلونة",
    "Rome": "روما",
    "Milan": "ميلانو",
    "Amsterdam": "أمستردام",
    "Brussels": "بروكسل",
    "Vienna": "فيينا",
    "Zurich": "زيورخ",
    "Stockholm": "ستوكهولم",
    "Oslo": "أوسلو",
    "Copenhagen": "كوبنهاغن",
    "Moscow": "موسكو",
    "Tokyo": "طوكيو",
    "Osaka": "أوساكا",
    "Seoul": "سيول",
    "Shanghai": "شنغهاي",
    "Hong Kong": "هونغ كونغ",
    "Singapore": "سنغافورة",
    "Mumbai": "مومباي",
    "Delhi": "نيودلهي",
    "Karachi": "كراتشي",
    "Lahore": "لاهور",
    "Sydney": "سيدني",
    "Melbourne": "ملبورن",
    "Toronto": "تورنتو",
    "Montreal": "مونتريال",
    "New York": "نيويورك",
    "Los Angeles": "لوس أنجلوس",
    "Chicago": "شيكاغو",
    "San Francisco": "سان فرانسيسكو",
    "Seattle": "سياتل",
    "Washington": "واشنطن",
    "Miami": "ميامي",
    "Boston": "بوسطن",
    "Houston": "هيوستن",
    "Dallas": "دالاس",
    "Atlanta": "أتلانتا",
    "Denver": "دنفر",
    "Phoenix": "فينيكس",
    "Mexico City": "مكسيكو سيتي",
    "São Paulo": "ساو باولو",
    "Buenos Aires": "بوينس آيرس",
    "Lima": "ليما",
    "Bogotá": "بوغوتا",
    "Santiago": "سانتياغو",
    "Lagos": "لاغوس",
    "Nairobi": "نيروبي",
    "Addis Ababa": "أديس أبابا",
    "Cape Town": "كيب تاون",
    "Johannesburg": "جوهانسبرغ",
}


def get_city_ar(english_name):
    """Return Arabic name of a city, or fallback to English."""
    if not english_name:
        return ''
    return _CITY_AR.get(english_name, english_name)


def get_country_info(english_name):
    """Return (arabic_name, iso_code) for an English country name.

    Falls back to (english_name, '') if unknown — ISO empty means no flag.
    """
    if not english_name:
        return ('', '')
    info = _COUNTRY_AR.get(english_name)
    if info:
        return info
    return (english_name, '')
