"""
Django settings for esco_project project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _
from decimal import Decimal

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# =============================================================================
# SENSITIVE SETTINGS - Imported from settings_local.py (not in git)
# الإعدادات الحساسة - مستوردة من settings_local.py (ليست في git)
# =============================================================================
try:
    from .settings_local import SECRET_KEY, DEBUG, ALLOWED_HOSTS
except ImportError:
    # Fallback defaults for development if settings_local.py doesn't exist
    # قيم افتراضية للتطوير إذا لم يكن settings_local.py موجوداً
    SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'fallback-insecure-key-for-dev-only')
    DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true'
    ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    # تطبيقاتك المخصصة أولاً - Your custom apps first
    'accounts.apps.AccountsConfig',  # ضع هذا أولاً - Put this first
    'core.apps.CoreConfig',
    'products.apps.ProductsConfig',
    'cart.apps.CartConfig',
    'orders.apps.OrdersConfig',
    'dashboard.apps.DashboardConfig',
    'checkout',
    'payment',
    'events',
    'blog.apps.BlogConfig',
    'chatbot.apps.ChatbotConfig',

    # تطبيقات Django المدمجة - Django built-in apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'widget_tweaks',

    # تطبيقات خارجية - Third-party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'django_cleanup.apps.CleanupConfig',
    'mptt',
    'import_export',
    'rest_framework',
    'django_filters',
    'django.contrib.humanize',
    'ckeditor',

]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
    'core.middleware.AgentReadyMiddleware',
]

ROOT_URLCONF = 'esco_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': False,  # Change this to False
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'core.context_processors.site_settings',
                'cart.context_processors.cart_context',
                'cart.context_processors.cart_preview_context',
            ],
            'loaders': [
                ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ]),
            ],
        },
    },
]

WSGI_APPLICATION = 'esco_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# =============================================================================
# DATABASE - Imported from settings_local.py (not in git)
# قاعدة البيانات - مستوردة من settings_local.py (ليست في git)
# =============================================================================
try:
    from .settings_local import DATABASES
except ImportError:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

DATABASES['default']['CONN_MAX_AGE'] = 600




AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# نموذج المستخدم المخصص - Custom user model
AUTH_USER_MODEL = 'accounts.User'

# عناوين تسجيل الدخول/الخروج - Login/logout URLs
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'core:home'
LOGOUT_REDIRECT_URL = 'core:home'

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ar'
TIME_ZONE = 'Asia/Amman'
USE_I18N = True
USE_L10N = True
USE_TZ = True
FORMAT_MODULE_PATH = ['esco_project.formats']

# اللغات المتاحة
LANGUAGES = [
    ('ar', _('العربية')),
    ('en', _('English')),
]

# مجلد ملفات الترجمة
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# إعدادات cookies للغة
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 days
LANGUAGE_COOKIE_DOMAIN = None
LANGUAGE_COOKIE_PATH = '/'
LANGUAGE_COOKIE_SECURE = False  # True in production with HTTPS
LANGUAGE_COOKIE_HTTPONLY = False
LANGUAGE_COOKIE_SAMESITE = None



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# ملفات الوسائط - Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# إعدادات Crispy Forms - Crispy Forms settings
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# =============================================================================
# EMAIL SETTINGS - Imported from settings_local.py (not in git)
# إعدادات البريد الإلكتروني - مستوردة من settings_local.py (ليست في git)
# =============================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_TIMEOUT = 10
try:
    from .settings_local import EMAIL_HOST, EMAIL_PORT, EMAIL_USE_TLS, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, DEFAULT_FROM_EMAIL
    try:
        from .settings_local import EMAIL_USE_SSL
    except ImportError:
        EMAIL_USE_SSL = False
except ImportError:
    # Fallback to console email for development if settings_local.py doesn't exist
    # الرجوع إلى إيميل الكونسول للتطوير إذا لم يكن settings_local.py موجوداً
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 465
    EMAIL_USE_TLS = False
    EMAIL_USE_SSL = True
    EMAIL_HOST_USER = ''
    EMAIL_HOST_PASSWORD = ''
    DEFAULT_FROM_EMAIL = 'noreply@example.com'



# إعدادات الجلسة - Session settings
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 days

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', # النظام الافتراضي
    'accounts.backends.RolePermissionBackend',  # النظام المخصص للأدوار
]

# حجم أقصى للصور
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'django.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 3,
        },
        'console': {
            'level': 'WARNING',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}


# 3. Session Configuration
# SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# SESSION_COOKIE_AGE = 86400 * 7  # 7 days
# SESSION_SAVE_EVERY_REQUEST = True  # Save session on every request
# SESSION_COOKIE_NAME = 'esco_sessionid'
# SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
# SESSION_COOKIE_HTTPONLY = True
# SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# 4. إعدادات إضافية للسلة (اختياري)
CART_SESSION_ID = 'cart'  # معرف السلة في الجلسة


# Cart Settings
DEFAULT_TAX_RATE = Decimal('0.16')
BASE_SHIPPING_COST = Decimal('0.00')
SHIPPING_WEIGHT_RATE = Decimal('0.00')
FREE_SHIPPING_THRESHOLD = Decimal('0.00')
MAX_CART_QUANTITY_PER_ITEM = 10



CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'django_cache'),
        'TIMEOUT': 3600,
        'OPTIONS': {
            'MAX_ENTRIES': 5000
        }
    }
}

CACHE_MIDDLEWARE_SECONDS = 120
CACHE_MIDDLEWARE_KEY_PREFIX = 'esco'

SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True



# مسارات تسجيل الدخول
# LOGIN_URL = 'dashboard:dashboard_login'
# LOGIN_REDIRECT_URL = 'dashboard:dashboard_home'
# LOGOUT_REDIRECT_URL = 'dashboard:dashboard_login'