# Generated by Django 5.2.13 on 2026-04-27 18:22

import blog.models
import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_categoryfaq_categorylandingcontent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='الرابط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('description_en', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome class مثل fa-tools', max_length=50, verbose_name='الأيقونة')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='وصف SEO')),
            ],
            options={
                'verbose_name': 'تصنيف المدونة',
                'verbose_name_plural': 'تصنيفات المدونة',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الوسم')),
                ('name_en', models.CharField(blank=True, max_length=50, verbose_name='Tag')),
                ('slug', models.SlugField(allow_unicode=True, max_length=60, unique=True, verbose_name='الرابط')),
            ],
            options={
                'verbose_name': 'وسم',
                'verbose_name_plural': 'الوسوم',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='العنوان')),
                ('title_en', models.CharField(blank=True, max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=280, unique=True, verbose_name='الرابط')),
                ('excerpt', models.TextField(blank=True, help_text='ملخص قصير يظهر في قائمة المقالات', max_length=300, verbose_name='المقتطف')),
                ('excerpt_en', models.TextField(blank=True, max_length=300, verbose_name='Excerpt')),
                ('content', ckeditor.fields.RichTextField(verbose_name='المحتوى')),
                ('content_en', ckeditor.fields.RichTextField(blank=True, verbose_name='Content')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to=blog.models.upload_blog_image, verbose_name='الصورة الرئيسية')),
                ('featured_image_alt', models.CharField(blank=True, max_length=200, verbose_name='وصف الصورة')),
                ('featured_image_alt_en', models.CharField(blank=True, max_length=200, verbose_name='Image Alt')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('archived', 'مؤرشف')], default='draft', max_length=10, verbose_name='الحالة')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مقال مميز')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='السماح بالتعليقات')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('reading_time', models.PositiveIntegerField(default=5, verbose_name='وقت القراءة (دقائق)')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='وصف SEO')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, verbose_name='كلمات مفتاحية')),
                ('canonical_url', models.URLField(blank=True, verbose_name='الرابط الأساسي')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory', verbose_name='التصنيف')),
                ('related_categories', models.ManyToManyField(blank=True, related_name='blog_posts', to='products.category', verbose_name='فئات ذات صلة')),
                ('related_products', models.ManyToManyField(blank=True, related_name='blog_posts', to='products.product', verbose_name='منتجات ذات صلة')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.blogtag', verbose_name='الوسوم')),
            ],
            options={
                'verbose_name': 'مقال',
                'verbose_name_plural': 'المقالات',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['-published_at', 'status'], name='blog_blogpo_publish_2530e0_idx'), models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx'), models.Index(fields=['status'], name='blog_blogpo_status_9c1956_idx')],
            },
        ),
    ]
