# Generated by Django 5.2.13 on 2026-04-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blogpost',
            name='blog_blogpo_slug_361555_idx',
        ),
    ]
