# Generated by Django 5.2.13 on 2026-04-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_blog_blogpo_slug_361555_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='card_icon',
            field=models.CharField(blank=True, default='fa-newspaper', help_text='Font Awesome icon class', max_length=50, verbose_name='أيقونة البطاقة'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='card_icon_color',
            field=models.CharField(blank=True, choices=[('#2563eb', 'أزرق'), ('#dc2626', 'أحمر'), ('#16a34a', 'أخضر'), ('#d97706', 'برتقالي'), ('#7c3aed', 'بنفسجي'), ('#0891b2', 'سماوي'), ('#e11d48', 'وردي'), ('#4b5563', 'رمادي')], default='#2563eb', max_length=20, verbose_name='لون الأيقونة'),
        ),
    ]
