# Generated by Django 5.2.13 on 2026-04-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_add_card_icon_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='card_icon_color',
            field=models.CharField(blank=True, choices=[('#2563eb', 'أزرق'), ('#1d4ed8', 'أزرق داكن'), ('#3b82f6', 'أزرق فاتح'), ('#0ea5e9', 'أزرق سماوي'), ('#0891b2', 'سماوي'), ('#06b6d4', 'تركوازي'), ('#0d9488', 'أخضر مزرق'), ('#16a34a', 'أخضر'), ('#059669', 'زمردي'), ('#65a30d', 'أخضر زيتي'), ('#ca8a04', 'ذهبي'), ('#d97706', 'برتقالي'), ('#ea580c', 'برتقالي داكن'), ('#dc2626', 'أحمر'), ('#b91c1c', 'أحمر داكن'), ('#e11d48', 'وردي'), ('#db2777', 'فوشيا'), ('#9333ea', 'بنفسجي'), ('#7c3aed', 'بنفسجي فاتح'), ('#6d28d9', 'نيلي'), ('#4f46e5', 'نيلي فاتح'), ('#475569', 'رمادي أزرق'), ('#4b5563', 'رمادي'), ('#1e293b', 'كحلي')], default='#2563eb', max_length=20, verbose_name='لون الأيقونة'),
        ),
    ]
