# Generated by Django 5.2.13 on 2026-04-28 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_expand_icon_color_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='السؤال')),
                ('question_en', models.CharField(blank=True, max_length=300, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('answer_en', models.TextField(blank=True, verbose_name='Answer')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='blog.blogpost', verbose_name='المقال')),
            ],
            options={
                'verbose_name': 'سؤال شائع للمقال',
                'verbose_name_plural': 'الأسئلة الشائعة للمقالات',
                'ordering': ['sort_order'],
            },
        ),
    ]
