# Generated by Django 5.2.13 on 2026-06-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_add_blogpostfaq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='card_icon_color',
            field=models.CharField(blank=True, default='#2563eb', help_text='كود اللون بصيغة HEX مثل #2563eb', max_length=20, verbose_name='لون الأيقونة'),
        ),
    ]
