# Generated by Django 5.2.13 on 2026-06-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_icon_color_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='card_display_mode',
            field=models.CharField(choices=[('image', 'صورة'), ('icon', 'أيقونة ولون')], default='image', help_text='اختر عرض صورة أو أيقونة ولون على بطاقة المقال', max_length=10, verbose_name='طريقة عرض البطاقة'),
        ),
    ]
