# Generated by Django 5.2.4 on 2025-07-11 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_session', to='orders.order', verbose_name='الطلب'),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='checkout_co_code_dc11db_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active'], name='checkout_co_is_acti_648c25_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['start_date', 'end_date'], name='checkout_co_start_d_4d20c4_idx'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='checkout.coupon', verbose_name='الكوبون'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='orders.order', verbose_name='الطلب'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to='checkout.paymentmethod', verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='checkout_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='checkout.checkoutsession', verbose_name='جلسة الدفع'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='orders.order', verbose_name='الطلب'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='checkout.paymentmethod', verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to='checkout.shippingmethod', verbose_name='طريقة الشحن'),
        ),
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together={('coupon', 'user', 'order')},
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['order'], name='checkout_pa_order_i_5b4647_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['checkout_session'], name='checkout_pa_checkou_75a0fb_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_id'], name='checkout_pa_transac_3655ee_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='checkout_pa_status_25af30_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['created_at'], name='checkout_pa_created_7d064d_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(fields=['user'], name='checkout_ch_user_id_cddb8e_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(fields=['session_key'], name='checkout_ch_session_15062a_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(fields=['created_at'], name='checkout_ch_created_c15d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(fields=['is_completed'], name='checkout_ch_is_comp_1c70b3_idx'),
        ),
    ]
