# Generated by Django 5.2.4 on 2025-07-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='description_en',
            field=models.TextField(blank=True, help_text='وصف طريقة الدفع المعروض للمستخدم', verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='instructions_en',
            field=models.TextField(blank=True, help_text='تعليمات خاصة بطريقة الدفع', verbose_name='تعليمات'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='name_en',
            field=models.CharField(default=1, help_text='اسم طريقة الدفع المعروض للمستخدم', max_length=100, verbose_name='اسم طريقة الدفع'),
            preserve_default=False,
        ),
    ]
