# Generated by Django 5.2.1 on 2025-12-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'تم إرسال الطلب'), ('processing', 'قيد المعالجة'), ('confirmed', 'تم تأكيد الطلب'), ('closed', 'تم إغلاق الطلب'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
    ]
