# Generated by Django 5.2.13 on 2026-04-23 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_branch_sitesettings_pickup_enabled_and_more'),
        ('orders', '0003_add_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('delivery', 'توصيل'), ('pickup', 'استلام من الفرع')], default='delivery', max_length=20, verbose_name='طريقة الاستلام'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.branch', verbose_name='فرع الاستلام'),
        ),
    ]
