# Generated by Django 5.2.4 on 2025-07-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='product',
        #     name='positive_base_price',
        # ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='وصف الفئة', verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, help_text='English description (optional)', verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, verbose_name='الباركود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='الوصف الكامل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, max_length=200, verbose_name='وصف مختصر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='show_price',
            field=models.BooleanField(default=False, verbose_name='عرض السعر'),
        ),
        # migrations.RunSQL(
        #     sql="ALTER TABLE products_product DROP CONSTRAINT positive_base_price;",
        #     reverse_sql="ALTER TABLE products_product ADD CONSTRAINT positive_base_price CHECK (base_price > 0);"
        # )

    ]
