# Generated by Django 5.2.1 on 2025-06-01 09:36

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('image', models.ImageField(help_text='صورة مرفقة مع التقييم', upload_to=products.models.upload_review_image, verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, help_text='وصف اختياري للصورة', max_length=200, verbose_name='وصف الصورة')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productreview', verbose_name='التقييم')),
            ],
            options={
                'verbose_name': 'صورة تقييم',
                'verbose_name_plural': 'صور التقييمات',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['review'], name='products_re_review__a7c535_idx'), models.Index(fields=['sort_order'], name='products_re_sort_or_16ef1a_idx')],
            },
        ),
    ]
