# Generated by Django 5.2.4 on 2025-07-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_positive_base_price_and_more'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='product',
        #     name='positive_base_price',
        # ),
        migrations.AddField(
            model_name='product',
            name='attachment',
            field=models.FileField(blank=True, help_text='ملف مرفق للمنتج مثل كتالوج أو دليل استخدام (PDF، DOC)', null=True, upload_to='products/attachments/%Y/%m/', verbose_name='الملف المرفق'),
        ),
        migrations.AddField(
            model_name='product',
            name='attachment_description',
            field=models.TextField(blank=True, help_text='وصف قصير للملف المرفق بالعربية', verbose_name='وصف الملف المرفق'),
        ),
        migrations.AddField(
            model_name='product',
            name='attachment_description_en',
            field=models.TextField(blank=True, help_text='Short description for the attachment in English', verbose_name='Attachment Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='attachment_name',
            field=models.CharField(blank=True, help_text='اسم وصفي للملف المرفق بالعربية', max_length=100, verbose_name='اسم الملف المرفق'),
        ),
        migrations.AddField(
            model_name='product',
            name='attachment_name_en',
            field=models.CharField(blank=True, help_text='Descriptive name for the attachment in English', max_length=100, verbose_name='Attachment Name'),
        ),
    ]
