# Generated by Django 5.2.4 on 2025-07-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_positive_base_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='positive_base_price',
        ),
    ]
