# Generated by Django 5.2.1 on 2025-06-26 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_lft_category_rght_category_tree_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'متوفر'), ('out_of_stock', 'غير متوفر')], default='in_stock', max_length=20, verbose_name='حالة المخزون'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=16, help_text='نسبة الضريبة المضافة', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الضريبة'),
        ),
    ]
