# Generated by Django 5.2.1 on 2025-12-21 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_positive_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdiscount',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='اختر العلامة التجارية لتطبيق الخصم على جميع منتجاتها', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.brand', verbose_name='العلامة التجارية'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='application_type',
            field=models.CharField(choices=[('all_products', 'جميع المنتجات'), ('category', 'فئة محددة'), ('brand', 'علامة تجارية محددة'), ('category_and_brand', 'فئة وعلامة تجارية'), ('specific_products', 'منتجات محددة'), ('minimum_purchase', 'حد أدنى للشراء')], default='all_products', max_length=20, verbose_name='نوع التطبيق'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='category',
            field=models.ForeignKey(blank=True, help_text='اختر الفئة لتطبيق الخصم على جميع منتجاتها', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.category', verbose_name='الفئة'),
        ),
    ]
