# Generated by Django 5.2.1 on 2026-04-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_brand_to_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='show_prices',
            field=models.BooleanField(default=True, verbose_name='إظهار الأسعار'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed_amount', 'مبلغ ثابت')], default='percentage', max_length=20, verbose_name='نوع الخصم'),
        ),
    ]
