# Generated by Django 5.2.1 on 2025-12-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_attachment_product_attachment_description_and_more'),
        ('products', '0005_add_brand_to_discount'),
    ]

    operations = [
    ]
