# Generated by Django 5.2.1 on 2026-04-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_add_show_prices_to_brand'),
        ('products', '0006_merge_20251225_1943'),
    ]

    operations = [
    ]
