# Generated by Django 5.2.1 on 2026-04-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_product_notes_and_activity_log'),
        ('products', '0007_merge_20260419_0046'),
    ]

    operations = [
    ]
