# Generated by Django 5.2.13 on 2026-04-27 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_add_tracker_sort_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='السؤال')),
                ('question_en', models.CharField(blank=True, max_length=300, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('answer_en', models.TextField(blank=True, verbose_name='Answer')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'سؤال شائع للفئة',
                'verbose_name_plural': 'الأسئلة الشائعة للفئات',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CategoryLandingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان البطل')),
                ('hero_title_en', models.CharField(blank=True, max_length=200, verbose_name='Hero Title')),
                ('hero_description', models.TextField(blank=True, verbose_name='وصف البطل')),
                ('hero_description_en', models.TextField(blank=True, verbose_name='Hero Description')),
                ('long_description', models.TextField(blank=True, help_text='محتوى غني للصفحة يساعد في SEO', verbose_name='وصف مطول')),
                ('long_description_en', models.TextField(blank=True, verbose_name='Long Description')),
                ('buying_guide', models.TextField(blank=True, verbose_name='دليل الشراء')),
                ('buying_guide_en', models.TextField(blank=True, verbose_name='Buying Guide')),
                ('local_keywords', models.CharField(blank=True, help_text='مثال: أدوات كهربائية الأردن, عمان', max_length=300, verbose_name='كلمات محلية')),
                ('local_keywords_en', models.CharField(blank=True, max_length=300, verbose_name='Local Keywords')),
            ],
            options={
                'verbose_name': 'محتوى صفحة الفئة',
                'verbose_name_plural': 'محتويات صفحات الفئات',
            },
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_updated_30df3c_idx',
            old_name='products_pr_updated_9f1a2b_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_stock_q_ba97b5_idx',
            old_name='products_pr_stock_q_3e7c1d_idx',
        ),
        migrations.AddField(
            model_name='categoryfaq',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='products.category', verbose_name='الفئة'),
        ),
        migrations.AddField(
            model_name='categorylandingcontent',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landing_content', to='products.category', verbose_name='الفئة'),
        ),
    ]
