# Generated by Django 5.2.13 on 2026-04-28 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_categoryfaq_categorylandingcontent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_active', 'is_featured'], name='products_br_is_acti_e09143_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='products_ca_parent__1cafc9_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'is_featured'], name='products_ca_is_acti_60a61c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'is_active'], name='products_pr_status_c4a457_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'brand'], name='products_pr_categor_1e5c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'featured_until'], name='products_pr_is_feat_f4b061_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'is_active', '-published_at'], name='products_pr_status_7c3dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['product', 'attribute'], name='products_pr_product_c00cf1_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='products_pr_product_1b7905_idx'),
        ),
        migrations.AddIndex(
            model_name='productquestion',
            index=models.Index(fields=['product', 'is_public'], name='products_pr_product_505f62_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'is_approved'], name='products_pr_product_160d92_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['is_approved', 'created_at'], name='products_pr_is_appr_d06a3f_idx'),
        ),
        migrations.AddIndex(
            model_name='productsubscription',
            index=models.Index(fields=['user', 'is_active'], name='products_pr_user_id_f3771f_idx'),
        ),
        migrations.AddIndex(
            model_name='productsubscription',
            index=models.Index(fields=['product', 'subscription_type'], name='products_pr_product_b053d9_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='products_pr_product_66459e_idx'),
        ),
        migrations.AddIndex(
            model_name='productviewhistory',
            index=models.Index(fields=['user', 'created_at'], name='products_pr_user_id_e6c0f6_idx'),
        ),
        migrations.AddIndex(
            model_name='productviewhistory',
            index=models.Index(fields=['session_key', 'created_at'], name='products_pr_session_e9b3cb_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['is_active', 'is_featured'], name='products_ta_is_acti_16dc8c_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', 'created_at'], name='products_wi_user_id_ae095a_idx'),
        ),
    ]
