# Generated by Django 5.2.13 on 2026-06-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_searchsynonym_searchquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='return_info',
            field=models.TextField(blank=True, help_text='سطر واحد لكل نقطة. اتركه فارغاً لاستخدام النص الافتراضي', verbose_name='سياسة الإرجاع'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_info',
            field=models.TextField(blank=True, help_text='سطر واحد لكل نقطة. اتركه فارغاً لاستخدام النص الافتراضي', verbose_name='معلومات الشحن'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_general_info',
            field=models.BooleanField(default=True, verbose_name='عرض معلومات عامة'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_shipping_returns',
            field=models.BooleanField(default=True, verbose_name='عرض الشحن والإرجاع'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='منتج جديد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='show_price',
            field=models.BooleanField(default=True, verbose_name='عرض السعر'),
        ),
    ]
